### ISSUE TITLE
Question: State and future of veriform

### ISSUE THREAD

**Issue by geoah** [voucher/veriform#49]
Hey @tarcieri,

In search for what's out there in regards to a replacement for json/cbor that can be consistently hashed I bumped into TJSON and Veriform (as well as object hash) all of which are amazing projects.

They also all seem to stop dead in their tracks last year.
The most interesting to me is Veriform as it brings TJSON and content aware (structured I think you call it here) hashing.

So I was wondering if there is any plan to continue work on either of these projects and if not if you wouldn't mind pointing me to any difficulties or roadblocks in this attempt.

Thank you very much for your work.

Regards,
George

**Comment by tarcieri** [comment]
Hello! Thank you for your interest and compliments.

Veriform (and Voucher) is a/are project(s) I hope to resume work on sooner than later. If I were to guess, I'd hope I get around to working on them in early 2019.

Having a single content hashing algorithm that works across both the Veriform and TJSON encodings simply, unobtrusively, and without any sharp edges, weirdness, or "gotchas" are very much still a goal.

I saw your post to the ObjectHash list as well: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/objecthash/T5wSZA4OH6M/_9Xm32YABwAJ

I think ObjectHash now supports the features needed to switch to it outright (namely the addition of `r`-tagged raw binary data). In as much as Veriform defines its own almost-ObjectHash-but-not-quite, that may be unnecessary now.

**Comment by geoah** [comment]
That sounds amazing, thank you. I'll keep an eye on this for updates and see if I can be of any help.

Any links/docs/specs/etc you might have on veriform, and especially on the dual nature of it (both self-describing and supporting schemas) would be greatly appreciated. 

Thank you once again. :)

ps. What is voucher going to be btw?

**Comment by tarcieri** [comment]
Voucher is a rebranding of "zcred", a vaporware encrypted credential format which incorporates ideas from SPKI/SDSI, Macaroons, and Vanadium: https://github.com/zcred/zcred

It continues to be the itch I am trying to scratch by creating Veriform, however clearly a serialization format is an "ambitious" project in and of itself.
